CREATE TABLE IF NOT EXISTS tokens (
  token TEXT PRIMARY KEY,
  note TEXT,
  is_admin INTEGER DEFAULT 0,
  created TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS files (
  key TEXT PRIMARY KEY,
  owner TEXT NOT NULL,
  original_name TEXT NOT NULL,
  content_type TEXT NOT NULL,
  size INTEGER NOT NULL,
  uploaded TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_owner ON files(owner);
